pluginManagement {
    resolutionStrategy {
        eachPlugin {
            if (requested.id.id == 'net.minecraftforge.gradle') {
                useModule('net.minecraftforge.gradle:ForgeGradle:6.0.54')
            }
        }
    }
    repositories {
        gradlePluginPortal()
        maven { url = 'https://maven.minecraftforge.net/' }
        maven {
            url = 'https://repo.spongepowered.org/repository/maven-public/'
            content { includeGroup 'org.spongepowered' }
        }
    }
}

rootProject.name = 'rs_integration'
