package com.huanghuang.rsintegration.mods.botania;
import com.huanghuang.rsintegration.crafting.CraftPacketUtils;import com.huanghuang.rsintegration.crafting.ExtractionLedger;import com.huanghuang.rsintegration.crafting.IngredientSpec;import com.huanghuang.rsintegration.crafting.batch.AbstractBatchDelegate;import com.refinedmods.refinedstorage.api.network.INetwork;import com.refinedmods.refinedstorage.api.util.Action;import net.minecraft.core.BlockPos;import net.minecraft.resources.ResourceLocation;import net.minecraft.server.level.ServerLevel;import net.minecraft.server.level.ServerPlayer;import net.minecraft.world.entity.item.ItemEntity;import net.minecraft.world.item.ItemStack;import net.minecraft.world.item.crafting.Ingredient;import net.minecraft.world.level.block.entity.BlockEntity;import net.minecraft.world.phys.AABB;import vazkii.botania.api.brew.BrewContainer;import vazkii.botania.api.recipe.BotanicalBreweryRecipe;import vazkii.botania.common.block.block_entity.BreweryBlockEntity;import javax.annotation.Nonnull;import java.util.*;
public final class BotanicalBreweryBatchDelegate extends AbstractBatchDelegate { private ServerLevel level;private BlockPos pos;private BotanicalBreweryRecipe recipe;private INetwork network;private ItemStack expected=ItemStack.EMPTY;private boolean started;private Set<UUID> entitiesBefore=Set.of();
@Override public boolean validateAndInit(@Nonnull ServerPlayer p,@Nonnull ResourceLocation id,ResourceLocation dim,@Nonnull BlockPos at){pos=at;machineDim=dim;machineServer=p.getServer();level=dim==null?p.serverLevel():p.getServer().getLevel(net.minecraft.resources.ResourceKey.create(net.minecraft.core.registries.Registries.DIMENSION,dim));if(level==null||!(level.getBlockEntity(pos) instanceof BreweryBlockEntity))return false;var r=level.getRecipeManager().byKey(id).orElse(null);if(!(r instanceof BotanicalBreweryRecipe rr))return false;recipe=rr;var vial=net.minecraft.core.registries.BuiltInRegistries.ITEM.get(new ResourceLocation("botania","vial"));expected=rr.getOutput(new ItemStack(vial));network=CraftPacketUtils.resolveNetworkForCraft(p,level.dimension(),pos);return network!=null&&expected!=null&&!expected.isEmpty();}
@Override public List<IngredientSpec> getRequiredMaterials(){if(recipe==null)return null;List<IngredientSpec>s=new ArrayList<>();var vial=net.minecraft.core.registries.BuiltInRegistries.ITEM.get(new ResourceLocation("botania","vial"));s.add(new IngredientSpec(Ingredient.of(vial),1));for(Ingredient i:recipe.getIngredients())if(!i.isEmpty())s.add(new IngredientSpec(i,1));return s;}
@Override public boolean tryStartSingleCraft(@Nonnull ServerPlayer p){List<ItemStack> m=BotaniaDelegateSupport.extractAtomically(network,getRequiredMaterials());return !m.isEmpty()&&start(m);}
@Override public boolean tryStartSingleCraft(@Nonnull ServerPlayer p,@Nonnull ExtractionLedger l){return false;}@Override public boolean tryStartWithMaterials(@Nonnull ServerPlayer p,@Nonnull List<ItemStack>m,@Nonnull ExtractionLedger l){return start(m);}
private boolean start(List<ItemStack>m){if(!(level.getBlockEntity(pos) instanceof BreweryBlockEntity be)||m.isEmpty()||!(m.get(0).getItem() instanceof BrewContainer))return false;entitiesBefore=BotaniaDelegateSupport.snapshot(level,new AABB(pos).inflate(1.5));for(ItemStack s:m)if(!be.addItem(null,s,null))return false;started=true;markCraftStarted();return true;}
@Override protected boolean isMachineCraftFinished(@Nonnull ServerLevel l,@Nonnull BlockEntity b){return started&&!l.getEntitiesOfClass(ItemEntity.class,new AABB(pos).inflate(1.5),e->BotaniaDelegateSupport.isNew(e,entitiesBefore)&&ItemStack.isSameItem(e.getItem(),expected)).isEmpty();}
@Override public ItemStack collectResult(@Nonnull ServerPlayer p){for(ItemEntity e:level.getEntitiesOfClass(ItemEntity.class,new AABB(pos).inflate(1.5),x->BotaniaDelegateSupport.isNew(x,entitiesBefore)&&ItemStack.isSameItem(x.getItem(),expected))){ItemStack result=e.getItem().copy();e.discard();return result;}return ItemStack.EMPTY;}
@Override public ItemStack getExpectedOutput(){return expected.isEmpty()?null:expected.copy();}@Override public AABB getOutputCaptureRegion(){return pos==null?null:new AABB(pos).inflate(1.5);}@Override public BlockPos getMachinePos(){return pos;}@Override public void onBatchFinished(@Nonnull ServerPlayer p){resetState();}}