package com.huanghuang.rsintegration.mods.botania;
import com.huanghuang.rsintegration.crafting.*;import com.huanghuang.rsintegration.crafting.batch.AbstractBatchDelegate;import com.refinedmods.refinedstorage.api.network.INetwork;import com.refinedmods.refinedstorage.api.util.Action;import net.minecraft.core.BlockPos;import net.minecraft.resources.ResourceLocation;import net.minecraft.server.level.*;import net.minecraft.world.entity.item.ItemEntity;import net.minecraft.world.item.ItemStack;import net.minecraft.world.item.crafting.Ingredient;import net.minecraft.world.level.block.entity.BlockEntity;import net.minecraft.world.phys.AABB;import vazkii.botania.api.recipe.ElvenTradeRecipe;import vazkii.botania.common.block.block_entity.AlfheimPortalBlockEntity;import javax.annotation.Nonnull;import java.util.*;
public final class ElvenTradeBatchDelegate extends AbstractBatchDelegate {private ServerLevel level;private BlockPos pos;private ElvenTradeRecipe recipe;private INetwork network;private List<ItemStack> expected=List.of();private boolean started;private long startTick;private Set<UUID> entitiesBefore=Set.of();
@Override public boolean validateAndInit(@Nonnull ServerPlayer p,@Nonnull ResourceLocation id,ResourceLocation dim,@Nonnull BlockPos at){pos=at;machineDim=dim;machineServer=p.getServer();level=dim==null?p.serverLevel():p.getServer().getLevel(net.minecraft.resources.ResourceKey.create(net.minecraft.core.registries.Registries.DIMENSION,dim));if(level==null||!(level.getBlockEntity(pos) instanceof AlfheimPortalBlockEntity))return false;var r=level.getRecipeManager().byKey(id).orElse(null);if(!(r instanceof ElvenTradeRecipe rr))return false;recipe=rr;expected=rr.getOutputs().stream().map(ItemStack::copy).toList();network=CraftPacketUtils.resolveNetworkForCraft(p,level.dimension(),pos);return network!=null&&!expected.isEmpty();}
@Override public List<IngredientSpec> getRequiredMaterials(){List<IngredientSpec>s=new ArrayList<>();for(Ingredient i:recipe.getIngredients())if(!i.isEmpty())s.add(new IngredientSpec(i,1));return s;}
@Override public boolean tryStartSingleCraft(@Nonnull ServerPlayer p){List<ItemStack> m=BotaniaDelegateSupport.extractAtomically(network,getRequiredMaterials());return !m.isEmpty()&&start(m);}@Override public boolean tryStartSingleCraft(@Nonnull ServerPlayer p,@Nonnull ExtractionLedger l){return false;}@Override public boolean tryStartWithMaterials(@Nonnull ServerPlayer p,@Nonnull List<ItemStack>m,@Nonnull ExtractionLedger l){return start(m);}
private boolean start(List<ItemStack>m){if(!(level.getBlockEntity(pos) instanceof AlfheimPortalBlockEntity))return false;List<ItemStack> dynamic=recipe.getOutputs(m);if(dynamic==null||dynamic.isEmpty())return false;expected=dynamic.stream().map(ItemStack::copy).toList();entitiesBefore=BotaniaDelegateSupport.snapshot(level,new AABB(pos).inflate(3));for(ItemStack s:m){ItemEntity e=new ItemEntity(level,pos.getX()+.5,pos.getY()+1.5,pos.getZ()+.5,s.copy());e.setDeltaMovement(0,0,0);BotaniaDelegateSupport.protectOperationInput(e);level.addFreshEntity(e);}started=true;startTick=level.getGameTime();markCraftStarted();return true;}
private List<ItemEntity> outputs(){AABB box=new AABB(pos).inflate(3);return level.getEntitiesOfClass(ItemEntity.class,box,e->BotaniaDelegateSupport.isNew(e,entitiesBefore)&&level.getGameTime()>=startTick&&expected.stream().anyMatch(x->ItemStack.isSameItem(x,e.getItem())));}
@Override protected boolean isMachineCraftFinished(@Nonnull ServerLevel l,@Nonnull BlockEntity b){if(!started)return false;List<ItemEntity> found=outputs();for(ItemStack want:expected){int n=found.stream().filter(e->ItemStack.isSameItem(e.getItem(),want)).mapToInt(e->e.getItem().getCount()).sum();if(n<want.getCount())return false;}return true;}
@Override public ItemStack collectResult(@Nonnull ServerPlayer p){List<ItemStack>a=collectAllResults(p);return a.isEmpty()?ItemStack.EMPTY:a.get(0);}@Override public List<ItemStack> collectAllResults(@Nonnull ServerPlayer p){List<ItemStack>r=new ArrayList<>();for(ItemEntity e:outputs()){r.add(e.getItem().copy());e.discard();}return r;}@Override public boolean collectsPhysicalSecondaryOutputs(){return true;}
@Override public ItemStack getExpectedOutput(){return expected.isEmpty()?null:expected.get(0);}@Override public AABB getOutputCaptureRegion(){return new AABB(pos).inflate(3);}@Override public BlockPos getMachinePos(){return pos;}@Override public void onBatchFinished(@Nonnull ServerPlayer p){resetState();}}