package com.huanghuang.rsintegration.mods.botania;
import com.huanghuang.rsintegration.crafting.CraftPacketUtils;import com.huanghuang.rsintegration.crafting.ExtractionLedger;import com.huanghuang.rsintegration.crafting.IngredientSpec;import com.huanghuang.rsintegration.crafting.batch.AbstractBatchDelegate;import com.refinedmods.refinedstorage.api.network.INetwork;import com.refinedmods.refinedstorage.api.util.Action;import net.minecraft.core.BlockPos;import net.minecraft.resources.ResourceLocation;import net.minecraft.server.level.ServerLevel;import net.minecraft.server.level.ServerPlayer;import net.minecraft.world.entity.item.ItemEntity;import net.minecraft.world.item.ItemStack;import net.minecraft.world.item.crafting.Ingredient;import net.minecraft.world.level.block.entity.BlockEntity;import net.minecraft.world.phys.AABB;import vazkii.botania.api.recipe.TerrestrialAgglomerationRecipe;import vazkii.botania.common.block.block_entity.TerrestrialAgglomerationPlateBlockEntity;import javax.annotation.Nonnull;import java.util.*;
public final class TerraPlateBatchDelegate extends AbstractBatchDelegate {private ServerLevel level;private BlockPos pos;private TerrestrialAgglomerationRecipe recipe;private INetwork network;private ItemStack expected=ItemStack.EMPTY;private final Set<UUID> inputs=new HashSet<>();private boolean started;private long startTick;private Set<UUID> entitiesBefore=Set.of();
@Override public boolean validateAndInit(@Nonnull ServerPlayer p,@Nonnull ResourceLocation id,ResourceLocation dim,@Nonnull BlockPos at){pos=at;machineDim=dim;machineServer=p.getServer();level=dim==null?p.serverLevel():p.getServer().getLevel(net.minecraft.resources.ResourceKey.create(net.minecraft.core.registries.Registries.DIMENSION,dim));if(level==null||!(level.getBlockEntity(pos) instanceof TerrestrialAgglomerationPlateBlockEntity))return false;var r=level.getRecipeManager().byKey(id).orElse(null);if(!(r instanceof TerrestrialAgglomerationRecipe rr))return false;recipe=rr;expected=rr.getResultItem(level.registryAccess()).copy();network=CraftPacketUtils.resolveNetworkForCraft(p,level.dimension(),pos);return network!=null&&!expected.isEmpty();}
@Override public List<IngredientSpec> getRequiredMaterials(){if(recipe==null)return null;List<IngredientSpec>s=new ArrayList<>();for(Ingredient i:recipe.getIngredients())if(!i.isEmpty())s.add(new IngredientSpec(i,1));return s;}
@Override public boolean tryStartSingleCraft(@Nonnull ServerPlayer p){List<ItemStack> m=BotaniaDelegateSupport.extractAtomically(network,getRequiredMaterials());return !m.isEmpty()&&start(m);}@Override public boolean tryStartSingleCraft(@Nonnull ServerPlayer p,@Nonnull ExtractionLedger l){return false;}@Override public boolean tryStartWithMaterials(@Nonnull ServerPlayer p,@Nonnull List<ItemStack>m,@Nonnull ExtractionLedger l){return start(m);}
private boolean start(List<ItemStack>m){entitiesBefore=BotaniaDelegateSupport.snapshot(level,new AABB(pos).inflate(2));if(!(level.getBlockEntity(pos) instanceof TerrestrialAgglomerationPlateBlockEntity))return false;inputs.clear();for(ItemStack s:m){ItemEntity e=new ItemEntity(level,pos.getX()+.5,pos.getY()+1.05,pos.getZ()+.5,s.copy());e.setDeltaMovement(0,0,0);BotaniaDelegateSupport.protectOperationInput(e);if(!level.addFreshEntity(e))return false;inputs.add(e.getUUID());}started=true;startTick=level.getGameTime();markCraftStarted();return true;}
@Override protected boolean isMachineCraftFinished(@Nonnull ServerLevel l,@Nonnull BlockEntity b){return started&&l.getEntitiesOfClass(ItemEntity.class,new AABB(pos).inflate(2),e->BotaniaDelegateSupport.isNew(e,entitiesBefore)&&e.isAlive()&&ItemStack.isSameItem(e.getItem(),expected)&&l.getGameTime()>=startTick).stream().findAny().isPresent();}
@Override public ItemStack collectResult(@Nonnull ServerPlayer p){for(ItemEntity e:level.getEntitiesOfClass(ItemEntity.class,new AABB(pos).inflate(2),x->BotaniaDelegateSupport.isNew(x,entitiesBefore)&&x.isAlive()&&ItemStack.isSameItem(x.getItem(),expected))){ItemStack s=e.getItem().copy();e.discard();return s;}return ItemStack.EMPTY;}
@Override protected void clearMachineState(BlockEntity b,ServerPlayer p){for(UUID id:inputs){var e=level.getEntity(id);if(e instanceof ItemEntity item&&item.isAlive()){ItemStack s=item.getItem().copy();item.discard();if(!usingSharedLedger&&!s.isEmpty())network.insertItem(s,s.getCount(),Action.PERFORM);}}inputs.clear();}
@Override public ItemStack getExpectedOutput(){return expected.isEmpty()?null:expected;}@Override public AABB getOutputCaptureRegion(){return new AABB(pos).inflate(2);}@Override public BlockPos getMachinePos(){return pos;}@Override public void onBatchFinished(@Nonnull ServerPlayer p){inputs.clear();resetState();}}